[package]
name = "p1-rpc-client-example"
version = "0.1.0"
description = "Hello Solana - Part 1 - Most basic RpcClient usage"
edition = "2018"

[dependencies]
solana-client = "1.7.2"
solana-sdk = "1.7.2"
