[package]
name = "direct-sol-transfer"
version = "0.1.0"
description = "Hello Solana - Transfer SOLs between accounts"
edition = "2018"

[dependencies]
anchor-client = "0.11.0"
solana-client = "1.7.2"
solana-sdk = "1.7.2"
shellexpand = "2.1.0"
rand = "0.7.3"
